# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/conno/Documents/Stuff/UIUC/2024-2025/FALL/ECE385/final/repo/final_project/final_project.srcs/sources_1/ip/display_buffer_bram/display_buffer_bram.xci
# IP: The module: 'display_buffer_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/conno/Documents/Stuff/UIUC/2024-2025/FALL/ECE385/final/repo/final_project/final_project.gen/sources_1/ip/display_buffer_bram/display_buffer_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_buffer_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/conno/Documents/Stuff/UIUC/2024-2025/FALL/ECE385/final/repo/final_project/final_project.srcs/sources_1/ip/display_buffer_bram/display_buffer_bram.xci
# IP: The module: 'display_buffer_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/conno/Documents/Stuff/UIUC/2024-2025/FALL/ECE385/final/repo/final_project/final_project.gen/sources_1/ip/display_buffer_bram/display_buffer_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_buffer_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
