set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN N15 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[0]}]
set_property PACKAGE_PIN E16 [get_ports {hub75_addr[4]}]
set_property PACKAGE_PIN D11 [get_ports {hub75_addr[3]}]
set_property PACKAGE_PIN K16 [get_ports {hub75_addr[2]}]
set_property PACKAGE_PIN C12 [get_ports {hub75_addr[1]}]
set_property PACKAGE_PIN H17 [get_ports {hub75_addr[0]}]
set_property PACKAGE_PIN H16 [get_ports {hub75_blue[1]}]
set_property PACKAGE_PIN C11 [get_ports {hub75_blue[0]}]
set_property PACKAGE_PIN H18 [get_ports {hub75_green[1]}]
set_property PACKAGE_PIN G18 [get_ports {hub75_green[0]}]
set_property PACKAGE_PIN G16 [get_ports {hub75_red[1]}]
set_property PACKAGE_PIN D10 [get_ports {hub75_red[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_blue[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_blue[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_green[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_green[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_red[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_red[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_clk]
set_property PACKAGE_PIN K14 [get_ports hub75_clk]
set_property PACKAGE_PIN H14 [get_ports hub75_latch]
set_property PACKAGE_PIN J15 [get_ports hub75_oe]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_latch]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_oe]

connect_debug_port u_ila_0/probe0 [get_nets [list {obb1_pos_x[16]} {obb1_pos_x[17]} {obb1_pos_x[18]} {obb1_pos_x[19]} {obb1_pos_x[20]} {obb1_pos_x[21]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list display_frame_done]]

set_property IOSTANDARD LVCMOS25 [get_ports start_signal]
set_property PACKAGE_PIN J2 [get_ports start_signal]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 6 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {obb1_pos_x[16]} {obb1_pos_x[17]} {obb1_pos_x[18]} {obb1_pos_x[19]} {obb1_pos_x[20]} {obb1_pos_x[21]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list hub75_clk_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
