set_property PACKAGE_PIN N15 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports mosi]
set_property IOSTANDARD LVCMOS25 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports miso]
set_property IOSTANDARD LVCMOS25 [get_ports ss]
set_property PACKAGE_PIN J16 [get_ports miso]
set_property PACKAGE_PIN E15 [get_ports mosi]
set_property PACKAGE_PIN E14 [get_ports sclk]
set_property PACKAGE_PIN J14 [get_ports ss]



set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {miso_data[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mosi_data[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports start_button]
set_property PACKAGE_PIN J2 [get_ports start_button]

set_property PACKAGE_PIN C13 [get_ports {accelerometer_data[0]}]
set_property PACKAGE_PIN D14 [get_ports {accelerometer_data[2]}]
set_property PACKAGE_PIN D15 [get_ports {accelerometer_data[3]}]
set_property PACKAGE_PIN D16 [get_ports {accelerometer_data[4]}]
set_property PACKAGE_PIN F18 [get_ports {accelerometer_data[5]}]
set_property PACKAGE_PIN E17 [get_ports {accelerometer_data[6]}]
set_property PACKAGE_PIN D17 [get_ports {accelerometer_data[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {accelerometer_data[0]}]




set_property PACKAGE_PIN C17 [get_ports {mosi_data[7]}]
set_property PACKAGE_PIN B18 [get_ports {mosi_data[6]}]
set_property PACKAGE_PIN A17 [get_ports {mosi_data[5]}]
set_property PACKAGE_PIN B17 [get_ports {mosi_data[4]}]
set_property PACKAGE_PIN C18 [get_ports {mosi_data[3]}]
set_property PACKAGE_PIN D18 [get_ports {mosi_data[2]}]
set_property PACKAGE_PIN E18 [get_ports {mosi_data[1]}]
set_property PACKAGE_PIN G17 [get_ports {mosi_data[0]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {accelerometer_master/data_word_recv_logic[0]} {accelerometer_master/data_word_recv_logic[1]} {accelerometer_master/data_word_recv_logic[2]} {accelerometer_master/data_word_recv_logic[3]} {accelerometer_master/data_word_recv_logic[4]} {accelerometer_master/data_word_recv_logic[5]} {accelerometer_master/data_word_recv_logic[6]} {accelerometer_master/data_word_recv_logic[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {mosi_data_OBUF[0]} {mosi_data_OBUF[1]} {mosi_data_OBUF[2]} {mosi_data_OBUF[3]} {mosi_data_OBUF[4]} {mosi_data_OBUF[5]} {mosi_data_OBUF[7]}]]

set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[0]}]
set_property PACKAGE_PIN G17 [get_ports {data_word_send[7]}]
set_property PACKAGE_PIN C14 [get_ports {accelerometer_data[1]}]
set_property PACKAGE_PIN E18 [get_ports {data_word_send[6]}]
set_property PACKAGE_PIN D18 [get_ports {data_word_send[5]}]
set_property PACKAGE_PIN C18 [get_ports {data_word_send[4]}]
set_property PACKAGE_PIN B17 [get_ports {data_word_send[3]}]
set_property PACKAGE_PIN A17 [get_ports {data_word_send[2]}]
set_property PACKAGE_PIN B18 [get_ports {data_word_send[1]}]
set_property PACKAGE_PIN C17 [get_ports {data_word_send[0]}]

connect_debug_port u_ila_0/probe1 [get_nets [list {accelerometer_master/recv_data[0]} {accelerometer_master/recv_data[1]} {accelerometer_master/recv_data[2]} {accelerometer_master/recv_data[3]} {accelerometer_master/recv_data[4]} {accelerometer_master/recv_data[5]} {accelerometer_master/recv_data[6]} {accelerometer_master/recv_data[7]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[0]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[1]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[3]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[5]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[7]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[8]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {accelerometer_master/FSM_onehot_current_state_reg_n_0_[9]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list miso_IBUF]]

set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_send[8]}]
set_property PACKAGE_PIN D17 [get_ports {data_word_send[8]}]
set_property PACKAGE_PIN E17 [get_ports {data_word_send[9]}]
set_property PACKAGE_PIN F18 [get_ports {data_word_send[10]}]
set_property PACKAGE_PIN D16 [get_ports {data_word_send[11]}]
set_property PACKAGE_PIN D15 [get_ports {data_word_send[12]}]
set_property PACKAGE_PIN D14 [get_ports {data_word_send[13]}]
set_property PACKAGE_PIN C14 [get_ports {data_word_send[14]}]
set_property PACKAGE_PIN C13 [get_ports {data_word_send[15]}]

set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {data_word_recv[0]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_word_send_OBUF[0]} {data_word_send_OBUF[3]} {data_word_send_OBUF[7]} {data_word_send_OBUF[8]} {data_word_send_OBUF[9]} {data_word_send_OBUF[10]} {data_word_send_OBUF[11]} {data_word_send_OBUF[12]} {data_word_send_OBUF[13]} {data_word_send_OBUF[15]}]]

set_property IOSTANDARD LVCMOS25 [get_ports {x0[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x0[0]}]
set_property PACKAGE_PIN C13 [get_ports {x0[7]}]
set_property PACKAGE_PIN C14 [get_ports {x0[6]}]
set_property PACKAGE_PIN D14 [get_ports {x0[5]}]
set_property PACKAGE_PIN D15 [get_ports {x0[4]}]
set_property PACKAGE_PIN D16 [get_ports {x0[3]}]
set_property PACKAGE_PIN F18 [get_ports {x0[2]}]
set_property PACKAGE_PIN E17 [get_ports {x0[1]}]
set_property PACKAGE_PIN D17 [get_ports {x0[0]}]


set_property PACKAGE_PIN G17 [get_ports test_clock]
set_property IOSTANDARD LVCMOS25 [get_ports test_clock]
connect_debug_port u_ila_0/probe1 [get_nets [list {x0_OBUF[0]} {x0_OBUF[1]} {x0_OBUF[2]} {x0_OBUF[3]} {x0_OBUF[4]} {x0_OBUF[5]} {x0_OBUF[6]} {x0_OBUF[7]}]]

set_property PACKAGE_PIN G6 [get_ports {x[15]}]
set_property PACKAGE_PIN H6 [get_ports {x[14]}]
set_property PACKAGE_PIN C3 [get_ports {x[13]}]
set_property PACKAGE_PIN B3 [get_ports {x[12]}]
set_property PACKAGE_PIN E6 [get_ports {x[11]}]
set_property PACKAGE_PIN B4 [get_ports {x[10]}]
set_property PACKAGE_PIN C5 [get_ports {x[9]}]
set_property PACKAGE_PIN D5 [get_ports {x[8]}]
set_property PACKAGE_PIN D7 [get_ports {x[7]}]
set_property PACKAGE_PIN D6 [get_ports {x[6]}]
set_property PACKAGE_PIN C4 [get_ports {x[5]}]
set_property PACKAGE_PIN B5 [get_ports {x[4]}]
set_property PACKAGE_PIN C9 [get_ports {x[3]}]
set_property PACKAGE_PIN B11 [get_ports {x[2]}]
set_property PACKAGE_PIN C10 [get_ports {x[1]}]
set_property PACKAGE_PIN A11 [get_ports {x[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {x[0]}]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_word_recv_OBUF[0]} {data_word_recv_OBUF[1]} {data_word_recv_OBUF[2]} {data_word_recv_OBUF[3]} {data_word_recv_OBUF[4]} {data_word_recv_OBUF[5]} {data_word_recv_OBUF[6]} {data_word_recv_OBUF[7]} {data_word_recv_OBUF[8]} {data_word_recv_OBUF[9]} {data_word_recv_OBUF[10]} {data_word_recv_OBUF[11]} {data_word_recv_OBUF[12]} {data_word_recv_OBUF[13]} {data_word_recv_OBUF[14]} {data_word_recv_OBUF[15]}]]


set_property PACKAGE_PIN C13 [get_ports led]
set_property IOSTANDARD LVCMOS25 [get_ports led]

set_property PACKAGE_PIN C14 [get_ports led2]
set_property IOSTANDARD LVCMOS25 [get_ports led2]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {x_OBUF[0]} {x_OBUF[1]} {x_OBUF[2]} {x_OBUF[3]} {x_OBUF[4]} {x_OBUF[5]} {x_OBUF[6]} {x_OBUF[7]} {x_OBUF[8]} {x_OBUF[9]} {x_OBUF[10]} {x_OBUF[11]} {x_OBUF[12]} {x_OBUF[13]} {x_OBUF[14]} {x_OBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list clk_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list miso_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list mosi_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list sclk_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list ss_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list test_clock_OBUF]]
set_property IOSTANDARD LVCMOS25 [get_ports led3]
set_property PACKAGE_PIN D14 [get_ports led3]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
