set_property PACKAGE_PIN N15 [get_ports clk]
set_property PACKAGE_PIN D10 [get_ports {hub75_red[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_red[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_red[0]}]
set_property PACKAGE_PIN C11 [get_ports {hub75_blue[0]}]
set_property PACKAGE_PIN G16 [get_ports {hub75_red[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_blue[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_blue[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_green[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_green[0]}]
set_property PACKAGE_PIN H16 [get_ports {hub75_blue[1]}]
set_property PACKAGE_PIN H17 [get_ports {hub75_addr[0]}]
set_property PACKAGE_PIN K16 [get_ports {hub75_addr[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hub75_addr[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_clk]
set_property PACKAGE_PIN K14 [get_ports hub75_clk]
set_property PACKAGE_PIN G18 [get_ports {hub75_green[0]}]
set_property PACKAGE_PIN H18 [get_ports {hub75_green[1]}]
set_property PACKAGE_PIN E16 [get_ports {hub75_addr[4]}]
set_property PACKAGE_PIN C12 [get_ports {hub75_addr[1]}]
set_property PACKAGE_PIN D11 [get_ports {hub75_addr[3]}]
set_property PACKAGE_PIN H14 [get_ports hub75_latch]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_latch]
set_property PACKAGE_PIN J15 [get_ports hub75_oe]
set_property IOSTANDARD LVCMOS25 [get_ports hub75_oe]
set_property PACKAGE_PIN J2 [get_ports start_signal]
set_property IOSTANDARD LVCMOS25 [get_ports start_signal]

connect_debug_port u_ila_0/probe1 [get_nets [list dut/write_pixel_clk_BUFG]]
connect_debug_port u_ila_1/clk [get_nets [list write_pixel_clk_BUFG]]
connect_debug_port u_ila_1/probe0 [get_nets [list {write_addr[0]} {write_addr[1]} {write_addr[2]} {write_addr[3]} {write_addr[4]} {write_addr[5]} {write_addr[6]} {write_addr[7]} {write_addr[8]} {write_addr[9]} {write_addr[10]}]]
connect_debug_port u_ila_1/probe1 [get_nets [list sync_pdp_ram/write_en_bottom]]
connect_debug_port u_ila_1/probe2 [get_nets [list sync_pdp_ram/write_en_top]]
connect_debug_port dbg_hub/clk [get_nets write_pixel_clk_BUFG]




set_property PACKAGE_PIN C13 [get_ports test_led]
set_property IOSTANDARD LVCMOS25 [get_ports test_led]
connect_debug_port u_ila_1/probe2 [get_nets [list dut_n_3]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list slow_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {hub75_red_OBUF[0]} {hub75_red_OBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {hub75_addr_OBUF[0]} {hub75_addr_OBUF[1]} {hub75_addr_OBUF[2]} {hub75_addr_OBUF[3]} {hub75_addr_OBUF[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {hub75_blue_OBUF[0]} {hub75_blue_OBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {hub75_green_OBUF[0]} {hub75_green_OBUF[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list hub75_latch_OBUF]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {startup_state[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list clk_IBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list hub75_clk_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list slow_clk]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list start_signal_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
