# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/display_buffer_bram/display_buffer_bram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==display_buffer_bram || ORIG_REF_NAME==display_buffer_bram} -quiet] -quiet
